import { Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import './globals.css'
import Footer from "@/components/footer";

const inter = Inter({
  subsets: ['latin'], // Add this line
  preload: true,      // Optional, default is true
})

export const metadata = {
  title: "CareerPilot AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html
        lang="en"
        className="dark"
        suppressHydrationWarning
      >
        <body className={`${inter.className} relative min-h-screen overflow-x-hidden`}>

          {/* 🌌 Global Gradient Background */}
          <div className="fixed inset-0 -z-10 
            bg-gradient-to-br 
            from-indigo-50 
            via-white 
            to-purple-50
            dark:from-slate-950 
            dark:via-slate-900 
            dark:to-black"
          />

          {/* ✨ Glow Effects */}
          <div className="fixed top-20 left-1/2 -translate-x-1/2 
            w-[600px] h-[600px] 
            bg-indigo-500/20 blur-[120px] 
            rounded-full -z-10"
          />

          <div className="fixed bottom-0 right-0 
            w-[400px] h-[400px] 
            bg-purple-500/20 blur-[120px] 
            rounded-full -z-10"
          />

          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />

            <main className="relative z-10 min-h-screen">
              {children}
            </main>

            <Toaster richColors />
            <Footer />
          </ThemeProvider>

        </body>
      </html>
    </ClerkProvider>
  );
}
